version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Build container
          command: |
            docker build -t $DOCKER_REGISTRY_HOST/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$DOCKER_IMAGE_NAME:latest -t $DOCKER_REGISTRY_HOST/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$DOCKER_IMAGE_NAME:dev .

      - deploy:
          name: Build and push Docker image
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
            docker login $DOCKER_REGISTRY_HOST -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker push  $DOCKER_REGISTRY_HOST/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$DOCKER_IMAGE_NAME:latest;
            fi
            if [ "$CIRCLE_BRANCH" == "dev" ]; then
            docker login $DOCKER_REGISTRY_HOST -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker push  $DOCKER_REGISTRY_HOST/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$DOCKER_IMAGE_NAME:dev;
            fi
workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build:
          context: github-package-registry